# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm install -g mocha
    - run: npm run build --if-present
    - run: npm test tests/test.js

  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2
      - name: Build image 
        run: docker build -t sample/my-page .
      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600    
      - name: Tag image 
        run:
          docker tag sample/my-page registry.digitalocean.com/jose-container/nodejstest
      - name: Push image to DO Container Registry 
        run: docker push registry.digitalocean.com/jose-container/nodejstest
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.IP_DIGITALOCEAN}} # IP address of the server you wish to ssh into
          key: ${{secrets.ID_RSA}} # Private or public key of the server
          username: ${{ secrets.DIGITALOCEAN_USER }} # User of the server you want to ssh into
          script: |            
            cd /home/deployment 
            docker-compose up -d 
            echo 'Deployment successful to digital ocean' 
